"""add_submission

Revision ID: 8a386c42418d
Revises: df57d06e1ee5
Create Date: 2026-06-08 09:42:45.759309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a386c42418d'
down_revision = 'df57d06e1ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the submissionstatus enum type
    submission_status = postgresql.ENUM('in_progress', 'submitted', 'accepted', name='submissionstatus')
    submission_status.create(op.get_bind(), checkfirst=True)

    op.create_table('submission',
    sa.Column('id', sa.Integer(), sa.Identity(), nullable=False),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', submission_status, nullable=False),
    sa.Column('dataset_file_name', sa.String(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('collection_id', sa.String(), nullable=True),
    sa.Column('schema_id', sa.String(), nullable=True),
    sa.Column('record_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], name=op.f('submission_collection_id_fkey')),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], name=op.f('submission_record_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('submission_pkey')),
    sa.UniqueConstraint('doi', name=op.f('submission_doi_key'))
    )

    op.drop_table('package_audit')
    op.drop_table('record_package')
    op.drop_table('keyword')
    op.drop_table('keyword_audit')
    op.drop_table('resource')
    op.drop_table('package_tag_audit')
    op.drop_table('package_tag')
    op.drop_table('archive_resource')
    op.drop_table('archive')
    op.drop_table('package')
    op.drop_table('provider_user')
    op.drop_constraint(op.f('client_provider_id_fkey'), 'client', type_='foreignkey')
    op.drop_column('client', 'provider_id')
    op.drop_column('client', 'provider_specific')
    op.drop_constraint(op.f('collection_tag_keyword_fkey'), 'collection_tag', type_='foreignkey')
    op.drop_column('collection_tag', 'keyword_id')
    op.drop_column('collection_tag', 'vocabulary_id')
    op.drop_column('collection_tag_audit', '_keyword_id')
    op.drop_column('provider_audit', '_users')
    op.drop_column('record_audit', '_packages')
    op.drop_constraint(op.f('record_tag_keyword_fkey'), 'record_tag', type_='foreignkey')
    op.drop_column('record_tag', 'keyword_id')
    op.drop_column('record_tag', 'vocabulary_id')
    op.drop_column('record_tag_audit', '_keyword_id')
    op.drop_column('schema', 'template_uri')
    op.alter_column('vocabulary', 'scope_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vocabulary', 'scope_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('odp', 'oauth', 'client', name='scopetype'),
               nullable=False)
    op.create_foreign_key('vocabulary_scope_fkey', 'vocabulary', 'scope', ['scope_id', 'scope_type'], ['id', 'type'], ondelete='RESTRICT')
    op.drop_column('vocabulary', 'uri')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocabulary', sa.Column('uri', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('vocabulary_scope_fkey', 'vocabulary', type_='foreignkey')
    op.alter_column('vocabulary', 'scope_type',
               existing_type=sa.Enum('odp', 'oauth', 'client', name='scopetype'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vocabulary', 'scope_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('submission')
    submission_status = postgresql.ENUM('in_progress', 'submitted', 'accepted', name='submissionstatus')
    submission_status.drop(op.get_bind(), checkfirst=True)
    op.add_column('schema', sa.Column('template_uri', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('record_tag_audit', sa.Column('_keyword_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('record_tag', sa.Column('vocabulary_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('record_tag', sa.Column('keyword_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('record_tag_keyword_fkey'), 'record_tag', 'keyword', ['vocabulary_id', 'keyword_id'], ['vocabulary_id', 'id'], ondelete='RESTRICT')
    op.add_column('record_audit', sa.Column('_packages', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('provider_audit', sa.Column('_users', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('collection_tag_audit', sa.Column('_keyword_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('collection_tag', sa.Column('vocabulary_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('collection_tag', sa.Column('keyword_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('collection_tag_keyword_fkey'), 'collection_tag', 'keyword', ['vocabulary_id', 'keyword_id'], ['vocabulary_id', 'id'], ondelete='RESTRICT')
    op.add_column('client', sa.Column('provider_specific', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('client', sa.Column('provider_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('client_provider_id_fkey'), 'client', 'provider', ['provider_id'], ['id'], ondelete='SET NULL')
    op.create_table('provider_user',
    sa.Column('provider_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], name=op.f('provider_user_provider_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('provider_user_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('provider_id', 'user_id', name=op.f('provider_user_pkey'))
    )
    op.create_table('package',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('validity', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('schema_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('schema_type', postgresql.ENUM('metadata', 'tag', 'keyword', 'vocabulary', name='schematype'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('editing', 'submitted', 'in_review', 'archived', 'delete_pending', name='packagestatus'), autoincrement=False, nullable=False),
    sa.CheckConstraint("schema_type = 'metadata'::schematype", name='package_schema_type_check'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], name='package_provider_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['schema_id', 'schema_type'], ['schema.id', 'schema.type'], name='package_schema_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='package_pkey'),
    sa.UniqueConstraint('provider_id', 'key', name='package_provider_id_package_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('archive',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scope_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scope_type', postgresql.ENUM('odp', 'oauth', 'client', name='scopetype'), autoincrement=False, nullable=True),
    sa.Column('download_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('upload_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('filestore', 'website', name='archivetype'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scope_id', 'scope_type'], ['scope.id', 'scope.type'], name='archive_scope_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='archive_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('archive_resource',
    sa.Column('archive_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'valid', 'missing', 'corrupt', name='archiveresourcestatus'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['archive_id'], ['archive.id'], name=op.f('archive_resource_archive_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name=op.f('archive_resource_resource_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('archive_id', 'resource_id', name=op.f('archive_resource_pkey')),
    sa.UniqueConstraint('archive_id', 'path', name=op.f('archive_resource_archive_id_path_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('package_tag',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('package_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tag_type', postgresql.ENUM('package', 'collection', 'record', name='tagtype'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('vocabulary_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('keyword_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint("tag_type = 'package'::tagtype", name=op.f('package_tag_tag_type_check')),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], name=op.f('package_tag_package_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id', 'tag_type'], ['tag.id', 'tag.type'], name=op.f('package_tag_tag_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('package_tag_user_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vocabulary_id', 'keyword_id'], ['keyword.vocabulary_id', 'keyword.id'], name=op.f('package_tag_keyword_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('package_tag_pkey'))
    )
    op.create_table('package_tag_audit',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('command', postgresql.ENUM('insert', 'update', 'delete', name='auditcommand'), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('_package_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('_tag_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('_user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('_keyword_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('package_tag_audit_pkey'))
    )
    op.create_table('resource',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mimetype', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('size', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hash_algorithm', postgresql.ENUM('md5', 'sha256', name='hashalgorithm'), autoincrement=False, nullable=True),
    sa.Column('package_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'delete_pending', name='resourcestatus'), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.CheckConstraint('hash IS NULL OR hash_algorithm IS NOT NULL', name=op.f('resource_hash_algorithm_check')),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], name=op.f('resource_package_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('resource_pkey')),
    sa.UniqueConstraint('package_id', 'path', name=op.f('resource_package_id_path_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('keyword_audit',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('command', postgresql.ENUM('insert', 'update', 'delete', name='auditcommand'), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('_vocabulary_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('_parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('keyword_audit_pkey'))
    )
    op.create_table('keyword',
    sa.Column('vocabulary_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1001, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('proposed', 'approved', 'rejected', 'obsolete', name='keywordstatus'), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['vocabulary_id', 'parent_id'], ['keyword.vocabulary_id', 'keyword.id'], name=op.f('keyword_parent_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], name=op.f('keyword_vocabulary_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vocabulary_id', 'id', name=op.f('keyword_pkey')),
    sa.UniqueConstraint('vocabulary_id', 'key', name=op.f('keyword_vocabulary_id_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('record_package',
    sa.Column('record_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('package_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], name=op.f('record_package_package_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], name=op.f('record_package_record_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id', 'package_id', name=op.f('record_package_pkey')),
    sa.UniqueConstraint('package_id', name=op.f('record_package_package_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('package_audit',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('_provider_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('_resources', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('command', postgresql.ENUM('insert', 'update', 'delete', 'submit', 'cancel', name='packagecommand'), autoincrement=False, nullable=False),
    sa.Column('_schema_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('package_audit_pkey'))
    )
    # ### end Alembic commands ###
