"""add_submission

Revision ID: 8a386c42418d
Revises: df57d06e1ee5
Create Date: 2026-06-08 09:42:45.759309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a386c42418d'
down_revision = 'df57d06e1ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the submissionstatus enum type
    submission_status = postgresql.ENUM('in_progress', 'submitted', 'accepted', name='submissionstatus')    

    op.create_table('submission',
    sa.Column('id', sa.Integer(), sa.Identity(), nullable=False),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', submission_status, nullable=False),
    sa.Column('dataset_file_name', sa.String(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('collection_id', sa.String(), nullable=True),
    sa.Column('schema_id', sa.String(), nullable=True),
    sa.Column('record_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], name=op.f('submission_collection_id_fkey')),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], name=op.f('submission_record_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('submission_pkey')),
    sa.UniqueConstraint('doi', name=op.f('submission_doi_key'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission')
    submission_status = postgresql.ENUM('in_progress', 'submitted', 'accepted', name='submissionstatus')
    submission_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
