"""created submission

Revision ID: aa889dea01cc
Revises: b7dd3a950ed5
Create Date: 2026-04-09 10:44:20.329844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa889dea01cc'
down_revision = 'b7dd3a950ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'submitted', 'accepted', name='submissionstatus'), nullable=False),
    sa.Column('dataset_file_name', sa.String(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('collection_id', sa.String(), nullable=True),
    sa.Column('schema_id', sa.String(), nullable=True),
    sa.Column('record_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi')
    )
    op.drop_index(op.f('idx_download_audit_client_id'), table_name='download_audit')
    op.drop_index(op.f('idx_download_audit_meta'), table_name='download_audit', postgresql_using='gin')
    op.drop_index(op.f('idx_download_audit_meta_download_type'), table_name='download_audit', postgresql_using='gin')
    op.drop_index(op.f('idx_download_audit_meta_email'), table_name='download_audit', postgresql_using='gin')
    op.drop_index(op.f('idx_download_audit_meta_organisation'), table_name='download_audit', postgresql_using='gin')
    op.drop_index(op.f('idx_download_audit_timestamp'), table_name='download_audit')
    op.drop_index(op.f('idx_download_audit_timestamp_client_id'), table_name='download_audit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_download_audit_timestamp_client_id'), 'download_audit', [sa.literal_column('timestamp DESC'), 'client_id'], unique=False)
    op.create_index(op.f('idx_download_audit_timestamp'), 'download_audit', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_download_audit_meta_organisation'), 'download_audit', [sa.literal_column("(meta -> 'organisation'::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_download_audit_meta_email'), 'download_audit', [sa.literal_column("(meta -> 'email'::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_download_audit_meta_download_type'), 'download_audit', [sa.literal_column("(meta -> 'download_type'::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_download_audit_meta'), 'download_audit', ['meta'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_download_audit_client_id'), 'download_audit', ['client_id'], unique=False)
    op.drop_table('submission')
    # ### end Alembic commands ###
